version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "src/rider/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(maint)"
    target-branch: "develop"
    ignore:
      - dependency-name: "org.jetbrains.kotlin.jvm"
        # kotlin version needs to match the intellij-platform version.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(maint)"
    target-branch: "develop"
  
