# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 4
style:
  ReturnCount:
    max: 10
  LoopWithTooManyJumpStatements:
    maxJumpCount: 5
  MaxLineLength:
    maxLineLength: 120
    excludes: ["**/test/**", "**/tests/**"] 