name: Build

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  PUBLISH_TOKEN: ${{ secrets.JB_PUBLISH_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-12 ]

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      # Validates the gradle wrappers and saves us from getting malicious PRs
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@216d1ad2b3710bf005dc39237337b9673fd8fcd5 # v3.3.2

      # Setup Java 11 environment which is needed to build
      - name: Setup Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup dotnet 6 (and 2.1 for Wyam, 3.1 for gitReleaseManager, 5.0 for gitVersion)
      - name: Setup dotnet
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # install libgit2-dev on ubuntu, so libgit2sharp works
      - name: Install libgit-dev
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libgit2-dev

      # Cache Cake tools
      - name: Cache Tools
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: See the available space
        if: runner.os != 'Windows'
        run: |
          echo "tmp points to ${{ runner.temp }}"
          df -h

      - name: See the available space
        if: runner.os == 'Windows'
        run: |
          echo "tmp points to ${{ runner.temp }}"
          Get-Volume

      - name: Build project
        uses: cake-build/cake-action@1223b6fa067ad192159f43b50cd4f953679b0934 # v2.0.0
        with:
          script-path: recipe.cake
          target: CI
          cake-version: tool-manifest

      # currently, Cake.Recipe does not upload artifacts when run on gh-actions
      - name: Upload Issues
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if:  runner.os == 'Windows'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*