name: Build

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  PUBLISH_TOKEN: ${{ secrets.JB_PUBLISH_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-12 ]

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      # Validates the gradle wrappers and saves us from getting malicious PRs
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0

      # Setup Java 11 environment which is needed to build
      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup dotnet 6 (and 2.1 for Wyam, 3.1 for gitReleaseManager, 5.0 for gitVersion)
      - name: Setup dotnet
        uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # install libgit2-dev on ubuntu, so libgit2sharp works
      - name: Install libgit-dev
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libgit2-dev

      # Cache Cake tools
      - name: Cache Tools
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: See the available space
        if: runner.os != 'Windows'
        run: |
          echo "tmp points to ${{ runner.temp }}"
          df -h

      - name: See the available space
        if: runner.os == 'Windows'
        run: |
          echo "tmp points to ${{ runner.temp }}"
          Get-Volume

      - name: Build project
        uses: cake-build/cake-action@1223b6fa067ad192159f43b50cd4f953679b0934 # v2.0.0
        with:
          script-path: recipe.cake
          target: CI
          cake-version: tool-manifest

      # currently, Cake.Recipe does not upload artifacts when run on gh-actions
      - name: Upload Issues
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if:  runner.os == 'Windows'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*