name: Verify

on:
  workflow_run:
    workflows: ["Build"]
    branches: ["develop"]
    types:
      - completed

jobs:
  verify:
    runs-on: windows-2022
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      # Setup Java 11 environment which is needed to build
      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup dotnet 6 (and 2.1 for Wyam, 3.1 for gitReleaseManager, 5.0 for gitVersion)
      - name: Setup dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            2.1.x
            3.1.x
            5.0.x
            6.0.x

      # Cache Cake tools
      - name: Cache Tools
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: See the available space
        run: |
          echo "tmp points to ${{ runner.temp }}"
          Get-Volume

      - name: Build project
        uses: cake-build/cake-action@1223b6fa067ad192159f43b50cd4f953679b0934 # v2.0.0
        with:
          script-path: recipe.cake
          target: Run-Plugin-Verifier
          cake-version: tool-manifest
          arguments: |
            enable-verifier: true
